export { TabsRoot as Root } from './root/tabs-root'
export { TabsPanel as Panel } from './panel/tabs-panel'
export { TabsPanelContent as PanelContent } from './panel-content/tabs-panel-content'
export { TabsList as List } from './list/tabs-list'
export { TabsTab as Tab } from './tab/tabs-tab'
export { TabsIndicator as Indicator } from './indicator/tabs-indicator'